name: Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Python
      run: sudo apt-get update && sudo apt-get install -y python3.9
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        source env/bin/activate
        pytest

    - name: Start Flask App
      env:
        FLASK_APP: app.py
      run: |
        source env/bin/activate
        flask run --host=0.0.0.0
