name: Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Python
      run: sudo apt-get update && sudo apt-get install -y python3.9
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build and deploy
      run: |
        flask build
        cp -R static $GITHUB_WORKSPACE
        cp -R templates $GITHUB_WORKSPACE
        cp app.py $GITHUB_WORKSPACE
        cp requirements.txt $GITHUB_WORKSPACE
    
    - name: Configure Git
      run: |
        git config --global user.name $NAME_USER
    
    - name: Deploy to GitHub Pages
      run: |
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy"
        git push --force --set-upstream origin gh-pages
